# Generated by Django 4.2.4 on 2023-09-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puntuacion',
            name='practice_count',
        ),
        migrations.AlterField(
            model_name='puntuacion',
            name='puntaje',
            field=models.CharField(default='0/0', max_length=10),
        ),
    ]
