# Generated by Django 4.2.4 on 2023-08-31 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_puntuacion_tiempo_empleado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puntuacion',
            name='tiempo_empleado',
        ),
    ]
