# Generated by Django 4.2.4 on 2023-08-18 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_ejercicio_puntuacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejercicio',
            name='tema',
        ),
    ]
