# Generated by Django 4.2.4 on 2023-08-18 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_ejercicio_tema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='ejercicios',
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='material',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.material'),
        ),
    ]
